import typing as t
from types import CodeType
from types import FrameType

def replace_constants(code: CodeType, consts: tuple) -> None: ...
def get_stack(frame: FrameType) -> dict[int, t.Any]: ...
def replace_in_tuple(tup: tuple, item: t.Any, replacement: t.Any) -> None: ...
def propagate_trace() -> None: ...
