name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typing:
    runs-on: "ubuntu-latest"

    name: Type checking
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install hatch

      - name: Type checking
        run: |
          hatch run lint:typing

  style:
    runs-on: "ubuntu-latest"

    name: Style
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install hatch

      - name: Linting
        run: |
          hatch run lint:style
